"""
What happens when a generated question reaches someone who cannot check it.

THE DISTINCTION FROM THE VALIDATOR
-----------------------------------
`validator/` asks whether the GENERATOR is fit to produce questions at all,
measured against a labelled corpus before anyone sees its output. This module
is about the ones that get through: a validator with 90% specificity is a
validator that passes one bad item in ten, and at any real volume that is a
wrong question in front of a learner who has no way to know.

So the two are complements. The validator lowers the rate. Nothing lowers it
to zero, and a system that only had the validator would be one where a wrong
question is found by the person it misleads, silently, with no way to say so.

WHAT IS RECORDED, AND WHY IT IS THE WHOLE PROVENANCE
-----------------------------------------------------
A report carries the question's source, chunk, locator, extraction confidence,
validation status and the model that wrote it -- captured AT REPORT TIME, not
looked up later. Questions get regenerated, chunks get re-ingested and models
get promoted, so a report that stored only `question_id` would, by the time
anyone read it, describe a question that no longer exists in the form that was
complained about.

THE SCOPE STATEMENT IS NOT LEGAL BOILERPLATE
----------------------------------------------
`SCOPE_STATEMENT` is shown in the app because a learner revising for a
postgraduate medical exam is exactly the person who might act on a
model-generated claim. Saying plainly what this is -- a revision aid built
from their own uploads, not a clinical reference and not a source of truth --
is the honest minimum, and it belongs on the screen rather than in a terms
document nobody opens.
"""

from __future__ import annotations

import json

from .db import Database, new_id, now_iso

#: Shown in the app, not buried in terms. Kept here rather than in the client
#: so the server and every client surface say the same words.
SCOPE_STATEMENT = (
    "Quintek is a revision aid. Its questions are generated by a language model "
    "from the material you upload, and they can be wrong -- including "
    "confidently and plausibly wrong. Check anything that matters against a "
    "textbook, a guideline or a clinician. This is not a clinical reference and "
    "must not be used to make a decision about a patient."
)

#: What a learner can say is wrong. Deliberately short: a long taxonomy shifts
#: the work of classification onto the person who just wanted to say "this is
#: wrong", and the free-text note carries what the categories cannot.
FACTUALLY_WRONG = "factually_wrong"
WRONG_ANSWER_KEYED = "wrong_answer_keyed"
NOT_IN_SOURCE = "not_in_source"
AMBIGUOUS = "ambiguous"
OFFENSIVE_OR_UNSAFE = "offensive_or_unsafe"
OTHER = "other"

REPORT_KINDS = (FACTUALLY_WRONG, WRONG_ANSWER_KEYED, NOT_IN_SOURCE, AMBIGUOUS,
                OFFENSIVE_OR_UNSAFE, OTHER)

#: Kinds that assert the CONTENT is wrong, as opposed to unclear or
#: distasteful. These are the ones that bear on whether the generator is fit,
#: so they are the ones `gold_candidates()` offers for adjudication.
CONTENT_ERROR_KINDS = (FACTUALLY_WRONG, WRONG_ANSWER_KEYED, NOT_IN_SOURCE)

OPEN = "open"
ACKNOWLEDGED = "acknowledged"
UPHELD = "upheld"
REJECTED = "rejected"
RESOLUTIONS = (OPEN, ACKNOWLEDGED, UPHELD, REJECTED)


class ReportRejected(ValueError):
    """The report cannot be recorded, and the message says why."""


def record(db: Database, *, user_id: str, question_id: str, kind: str,
           note: str = "") -> dict:
    """
    Record one report, with the question's provenance frozen into it.

    The ownership join is the caller's job and is done in `StudentAPI`; this
    refuses to write a report for a question it cannot read, which makes a
    missing join fail loudly rather than producing an orphan row.
    """
    if kind not in REPORT_KINDS:
        raise ReportRejected(
            f"unknown report kind {kind!r}; expected one of {', '.join(REPORT_KINDS)}")

    row = db.query_one(
        "SELECT q.id, q.stem, q.options_json, q.correct_index, q.source_id,"
        "       q.chunk_id, q.validation_status, q.generated_by_candidate_id,"
        "       q.prompt_version, ch.confidence AS chunk_confidence,"
        "       ch.needs_review AS chunk_needs_review, ch.locator_json"
        "  FROM questions q"
        "  LEFT JOIN source_chunks ch ON ch.id = q.chunk_id"
        " WHERE q.id = ?", (question_id,))
    if row is None:
        raise ReportRejected(f"no such question: {question_id}")

    # Frozen, not referenced. A question can be regenerated and a chunk
    # re-ingested; a report that only pointed at them would describe something
    # that no longer exists by the time anyone reads it.
    provenance = {
        "stem": row["stem"],
        "options": json.loads(row["options_json"] or "[]"),
        "correct_index": row["correct_index"],
        "source_id": row["source_id"],
        "chunk_id": row["chunk_id"],
        "locator": json.loads(row["locator_json"] or "{}"),
        "chunk_confidence": row["chunk_confidence"],
        "chunk_needs_review": bool(row["chunk_needs_review"]),
        "validation_status": row["validation_status"],
        "generated_by_candidate_id": row["generated_by_candidate_id"],
        "prompt_version": row["prompt_version"],
    }
    report_id = new_id("rpt")
    db.execute(
        "INSERT INTO question_reports (id, question_id, user_id, kind, note,"
        " provenance_json, resolution, created_at) VALUES (?,?,?,?,?,?,?,?)",
        (report_id, question_id, user_id, kind, (note or "").strip()[:4000],
         json.dumps(provenance), OPEN, now_iso()))
    return {"report_id": report_id, "question_id": question_id, "kind": kind,
            "resolution": OPEN, "provenance": provenance}


def for_user(db: Database, user_id: str) -> list[dict]:
    """Everything this learner has reported, newest first."""
    return [_inflate(r) for r in db.query(
        "SELECT * FROM question_reports WHERE user_id = ?"
        " ORDER BY created_at DESC", (user_id,))]


def for_question(db: Database, question_id: str) -> list[dict]:
    return [_inflate(r) for r in db.query(
        "SELECT * FROM question_reports WHERE question_id = ?"
        " ORDER BY created_at DESC", (question_id,))]


def open_reports(db: Database, *, limit: int = 200) -> list[dict]:
    """
    The queue. Ordered oldest first on purpose: a report that has waited
    longest is the one most likely to have been forgotten, and a newest-first
    queue is how a backlog becomes permanent.
    """
    return [_inflate(r) for r in db.query(
        "SELECT * FROM question_reports WHERE resolution = ?"
        " ORDER BY created_at LIMIT ?", (OPEN, limit))]


def resolve(db: Database, report_id: str, *, resolution: str,
            resolved_by: str, note: str = "") -> dict:
    """
    Close a report. `resolved_by` is required and must be a name.

    "Resolved" with nobody attached is the same failure as a review with no
    reviewer: it looks like something happened and cannot be questioned.
    """
    if resolution not in RESOLUTIONS or resolution == OPEN:
        raise ReportRejected(
            f"resolution must be one of {', '.join(r for r in RESOLUTIONS if r != OPEN)}")
    if not (resolved_by or "").strip():
        raise ReportRejected(
            "a resolution needs the name of whoever made it; an anonymous "
            "resolution is indistinguishable from nobody having looked")
    row = db.query_one("SELECT id, question_id FROM question_reports WHERE id = ?",
                       (report_id,))
    if row is None:
        raise ReportRejected(f"no such report: {report_id}")
    stamp = now_iso()
    db.execute(
        "UPDATE question_reports SET resolution = ?, resolved_by = ?,"
        " resolution_note = ?, resolved_at = ? WHERE id = ?",
        (resolution, resolved_by.strip(), (note or "").strip()[:4000],
         stamp, report_id))
    withdrawn = resolution == UPHELD and _withdraw(
        db, row["question_id"], report_id=report_id, by=resolved_by.strip(), at=stamp)
    out = _inflate(db.query_one(
        "SELECT * FROM question_reports WHERE id = ?", (report_id,)))
    out["question_withdrawn"] = bool(withdrawn)
    return out


def _withdraw(db: Database, question_id: str, *, report_id: str, by: str, at: str) -> bool:
    """An upheld report takes its question out of service.

    Upholding a report is an operator agreeing the question is wrong -- the
    content, the key, the source, or that it is unsafe. Until 2026-09-24 it
    changed only the report row, so a question an operator had just confirmed
    was keyed wrong went on being served as 'approved'. It is now 'flagged',
    which the one servability rule (ADR-030) already refuses everywhere, and
    the validation record says which report withdrew it and who upheld it.

    One-way. Re-resolving the report later does not put the question back:
    returning a withdrawn question to service is a fresh validation, not a
    change of mind on a report."""
    q = db.query_one("SELECT validation_status, validation_json FROM questions WHERE id = ?",
                     (question_id,))
    if q is None:
        return False
    try:
        record = json.loads(q["validation_json"] or "{}")
    except ValueError:
        record = {}
    record["withdrawn"] = {"report_id": report_id, "by": by, "at": at,
                           "previous_status": q["validation_status"]}
    db.execute("UPDATE questions SET validation_status = 'flagged', validation_json = ?"
               " WHERE id = ?", (json.dumps(record), question_id))
    return True


def gold_candidates(db: Database) -> list[dict]:
    """
    Reports asserting a CONTENT error, upheld or not yet judged.

    THE ROUTE FOR A GOLD ERROR FOUND BY SOMEONE OTHER THAN THE AUTHOR. The
    development corpus is model-authored and `label_status: unreviewed`; one
    clean item has already turned out to be wrong. A learner hitting a bad
    question in the app is finding the same class of defect from the other
    end, and without this it stops at their annoyance.

    This does NOT write to the corpus and must not. Adjudication is
    `validator/review.py` -- two named reviewers, blind, kappa reported. What
    this produces is the queue that feeds it: each entry carries the frozen
    provenance, so a reviewer can see the stem, the passage it came from, the
    extraction confidence and what the validator said at the time.
    """
    return [r for r in
            (_inflate(x) for x in db.query(
                "SELECT * FROM question_reports WHERE kind IN"
                f" ({','.join('?' * len(CONTENT_ERROR_KINDS))})"
                " AND resolution IN (?, ?) ORDER BY created_at",
                (*CONTENT_ERROR_KINDS, OPEN, UPHELD)))]


def _inflate(row) -> dict:
    out = dict(row)
    out["provenance"] = json.loads(out.pop("provenance_json") or "{}")
    return out
